language: ruby
rvm:
- 2.4.0
deploy:
  provider: heroku
  api_key:
    secure: V2tgenEjMVRf7ze3tdOMxlXN0xKSnbUmsy+xGm4BoEVTav7exj6JpnqrhYW9KqAZAYYSqTZ1CqZ8kM8rib2SJpdh7g7TShXxeH2p71FW+S5eld+r+4hqET0gqvDrexT8CJ3Syxh6/8HZOvNbzg90jAiXtmnfKI+Fc2yinKJRzGc=
  app: uncleclive
  on:
    repo: pikesley/uncle-clive
