language: ruby
rvm:
- 2.1.5
deploy:
  provider: heroku
  app: uncleclive
  api_key:
    secure: "nXDladi4HMHb5EOpWHf+BMHFaeJasHle3d/9Fnj+8aFPBGqeVmx4aQwNN1+26m2sQpXWoY9OkLcuuDOM1j5xZv4DEKyTnU7J66XDmE1giNYp6il2Kxg71iflLdJbpt2oPrUczLk9/28xhlkd8yau5ti+c7FgdRQNLJli7fEZpgk="
